### ISSUE TITLE
[Feature]  for window please :( 

### ISSUE THREAD

**Issue by omaru-ok** [margual56/radio-cli#18]
also provide it for window
as executable 
pre-compiled

**Comment by margual56** [comment]
Hi! Thank you for the suggestion.

Unfortunately I do not use windows so I cannot test the program to ensure it will work ok that platform. 

Also this uses mpv as the backend, and I'm not sure if the way I'm making the calls to that program is compatible with the windows version of mpv (or windows itself).

Luckily for you, if you want to have it on windows either way, you just need to [install rust](https://rustup.rs/#) and then run `cargo install --git https://github.com/margual56/radio-cli`.

That should install the program inside the cargo binary folder, and if that folder is in the windows path you should be able to run the program :)

**Comment by omaru-ok** [comment]
Thx, i still appreciate that :D
