### ISSUE TITLE
[Feature] - Show name of song 

### ISSUE THREAD

**Issue by julienrat** [margual56/radio-cli#24]
Is it possible to show the name of the song is played, in the title of the terminal window for example ?
Many thx for the job !
Cheers
julien

**Comment by margual56** [comment]
Hi! Thanks for the suggestion, I think that's a good idea. However, I don't have access to the song currently playing. What I have access to is the radio station being played.

I have added it to the [dev branch](https://github.com/margual56/radio-cli/tree/dev). Give it a try! Tell me what you think.

**Comment by margual56** [comment]
@julienrat Thank you for your contribution and the code snippet you've provided, I'm glad to see your interest in this feature!

To streamline the process and ensure that the proposed changes are properly reviewed and integrated, I'd kindly request you to create a pull request with your code. This will make it easier for everyone to test and collaborate on this feature.

If you encounter any issues during this process or need guidance on how to structure your pull request, feel free to ask for help.

Thank you again for your involvement, I look forward to reviewing your pull request.

**Comment by margual56** [comment]
@julienrat Seeing as you did not submit a pull request, I will merge the feature with only the station name being shown.

If in the future you want to contribute with your code, you are very welcome to do so :)
